//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Auto-generated designer for Default.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSC.Sample.WebApp
{
    public partial class Default
    {
        /// <summary>form1 control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>TimeLabel control.</summary>
        protected global::System.Web.UI.WebControls.Label TimeLabel;
    }
}
